id: P010608
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-20 10:16:18.626666
source_metadata:
  id: bdr:W2CZ7938
  title: འབྲོག་མི་ལོ་ཙཱ་བའི་རྣམ་ཐར་
  author: ''
  volumes:
    8e97560a1a7f4b2d862c378e30d53a94:
      image_group_id: I1KG3452
      title: ''
      volume_number: 1
      total_pages: 12
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
