id: IE6C5FD19
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T08:04:09+00:00'
last_modified: '2022-06-08T16:12:47.382578+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2CZ7938
  title: འབྲོག་མི་ལོ་ཙཱ་བའི་རྣམ་ཐར་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    E6E3:
      image_group_id: I1KG3452
      title: ''
      total_pages: 12
      order: 1
      base_file: E6E3.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
